name: Create SVG

on: [push]
#schedule:
#  # * is a special character in YAML so you have to quote this string
#  - cron:  '30 5,17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install dependencies
        run: pip install # libraries go here

      - name: Run program
        run: python createsvg.py

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Create new SVG"
          git push origin master

